name: release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: release
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub sources
      uses: actions/checkout@v2
    - name: Setup GitHub Packages
      uses: actions/setup-java@v1
      with:
        java-version: 9
    - name: Resolve from GitHub Packages
      run: ./mvnw -B -Pgithub.packages dependency:copy
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Setup Maven Central
      uses: actions/setup-java@v1
      with:
        java-version: 9
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_SIGNER_KEY }}
        gpg-passphrase: OSSRH_SIGNER_PASSPHRASE
    - name: Deploy to Maven Central
      id: deploy
      continue-on-error: true
      run: ./mvnw -B -Possrh com.github.genthaler:beanshell-maven-plugin:run build-helper:attach-artifact gpg:sign nexus-staging:deploy
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_SIGNER_PASSPHRASE: ${{ secrets.OSSRH_SIGNER_PASSPHRASE }}
    - name: Notify via Slack
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        job_name: Publish
        fields: job,repo,author,took
        custom_payload: |
          {
            attachments: [{
              color: '${{ steps.deploy.outcome }}' === 'success' ? 'good' : '${{ steps.deploy.outcome }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_JOB} of ${process.env.AS_REPO} (${process.env.GITHUB_REF.replace(/refs\/tags\//, '')}) by ${process.env.AS_AUTHOR.replace(/\<.*\>/, '')} completed in ${process.env.AS_TOOK}`,
            }]
          }
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: ${{ env.SLACK_WEBHOOK_URL != null }}
